### ISSUE TITLE
"You don't have permission to access this"

### ISSUE THREAD

**Issue by chrislind** [directus-community/agency-os#46]
Hi,
I'm testing out the agency-os and am using a generated token on our directus cloud to try and build the site. However I get this error:
```
 ERROR  Cannot start nuxt:  { errors:                                                                                                                                                                                                                                   11:54:43 AM
   [ { message: "You don't have permission to access this.", extensions: [Object] } ],
  response:
   Response {
     [Symbol(realm)]: null,
     [Symbol(state)]:
      { aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 403,
        timingInfo: [Object],
        cacheState: '',
        statusText: 'Forbidden',
        headersList: [HeadersList],
        urlList: [Array],
        body: [Object] },
     [Symbol(headers)]:
      HeadersList { cookies: null, [Symbol(headers map)]: [Map], [Symbol(headers map sorted)]: null } } }
```

I have tried the token directly on the directus rest api and it works fine. Like so:
https://MY_DIRECTUS_APP.directus.app/items/pages?fields[]=*.*.*.*.*&access_token=-MY_ACCESS_TOKEN

The token is created on an admin user. Is there some other step that needs to be taken to get this to work?

**Comment by bryantgillespie** [comment]
Couple things off the top of my head -

`You don't have permission to access this.` is a response from the Directus API which means it's at least reachable. 

1) Did you run the `directus-template-cli apply` command and used the AgencyOS template  against your cloud instance? Any errors there? 

2) Have you checked the permissions settings within your Directus instance? During the build process - it calls the Directus API and requests the `redirects` and `globals` collections. Public role access should be allowed for those and the other website collections. The template CLI should take care of setting those up properly for you but if there were errors during that script - it could have not properly loaded permissions.

**Comment by malipetek** [comment]
I digged a bit into this issue, however could not find what is wrong, when I run `yarn`/`yarn dev`, it executes [modules/directus/index.ts](https://github.com/directus-community/agency-os/blob/main/modules/directus/index.ts) and when requesting `redirects` it throws this error. 

I tried modifying this line 
[`const directus = createDirectus<Schema>(moduleOptions.rest.baseUrl).with(rest());
`](https://github.com/directus-community/agency-os/blob/a63547499dadf26c3922d0be4b1492bbd1281884/modules/directus/index.ts#L160C58-L160C58)
To this:
```js
// ** Build Logic **
log.log('process.env.DIRECTUS_SERVER_TOKEN ', process.env.DIRECTUS_SERVER_TOKEN);
const directus = createDirectus<Schema>(moduleOptions.rest.baseUrl)
	.with(rest())
	.with(staticToken(process.env.DIRECTUS_SERVER_TOKEN));
```

However I noticed something else, website api user has no permissions at all and "navigation items" are all empty. I think there is another issue here with the setup I am using.

<img width="880" alt="image" src="https://github.com/directus-community/agency-os/assets/13527277/ecd3babc-1ac5-4c98-8933-3db5701f0497">

<img width="651" alt="image" src="https://github.com/directus-community/agency-os/assets/13527277/dc8c3c97-7e08-4b5d-830b-ba1a5eb2d9e7">

I am using a docker compose without redis cache, also using cloudflare tunnel to expose this container to the internet at a subdomain: [portal.malipetek.dev](https://portal.malipetek.dev)
```yml
name: malipetek-dev
version: "3"
networks:
  cftunnel:
    external: true
  default:
    driver: bridge
services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    networks:
    - default

  directus:
    image: directus/directus:10.7.2
    ports:
      - 44444:8055
    networks:
      - cftunnel
      - default
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "m****k@gmail.com"
      ADMIN_PASSWORD: *****

      # These is helpful for local developement but should probably be removed in production
      CORS_ENABLED: 'true'
      REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      EXTENSIONS_AUTO_RELOAD: 'true'

      WEBSOCKETS_ENABLED: 'true'
      # The default config prevents importing files from 0.0.0.0. See https://docs.directus.io/self-hosted/config-options.html#security . This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''
```
